many refactor and style
EQUENOS/dislash.py pull request #35
Opened 2021-07-16 03:19 UTC by MisileLab

2021-07-16 07:31 UTC, m1raynee commented on dislash/interactions/message_components.py
> +    link = 5
```suggestion
    # fmt: off
    primary   = 1
    blurple   = 1

    secondary = 2
    grey      = 2
    gray      = 2

    success   = 3
    green     = 3

    danger    = 4
    red       = 4

    link      = 5
    # fmt: on
```

2021-07-16 07:40 UTC, m1raynee commented on dislash/slash_commands/slash_command.py
> +    MENTIONABLE = 9
```suggestion
    # fmt: off
    SUB_COMMAND       = 1
    SUB_COMMAND_GROUP = 2
    STRING            = 3
    INTEGER           = 4
    BOOLEAN           = 5
    USER              = 6
    CHANNEL           = 7
    ROLE              = 8
    MENTIONABLE       = 9
    # fmt: on
```

2021-07-16 07:43 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +# -----------------------------------+
```suggestion
# +-----------------------------------+
# |              Utils                |
# +-----------------------------------+

```

2021-07-16 07:43 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +# -----------------------------------+
```suggestion
# +-----------------------------------+
# |         Core and checks           |
# +-----------------------------------+

```

2021-07-16 07:46 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +                self._buckets = CooldownMapping(cooldown)
```suggestion
                self._buckets = CooldownMapping(cooldown, BucketType.default)
```
What is the reason for dropping this?

2021-07-16 07:49 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +               items):
```suggestion
        if any(getter(id=item) is not None if isinstance(item, int) else getter(name=item) is not None
        for item in items):
```
It looks better

2021-07-16 07:50 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +               items):
```suggestion
        if any(getter(id=item) is not None if isinstance(item, int) else getter(name=item) is not None
        for item in items):
```
Simmilar

2021-07-16 07:54 UTC, m1raynee commented on dislash/slash_commands/utils.py
> +        def always():
Strange, I think there is a magical meaning in the presence of this argument

2021-07-16 07:59 UTC, m1raynee commented on dislash/slash_commands/slash_client.py
>                      return False
```suggestion
```
Simmalar to [L99-L100](https://github.com/EQUENOS/dislash.py/pull/35/files#diff-3b70d3f8c8ad87ae86db4601fb6edd0980ed2243d9e1da6983ebc6c6f4146055L99-L100)

2021-07-16 08:06 UTC, m1raynee commented on dislash/slash_commands/slash_client.py
> +                    return True
```suggestion
check = lambda ctx: True
```
This is absolutely wrong. `message` out of nowhere?? I think some of the code just migrated here due to the incorrect operation of the automatic parser of your IDE.

2021-07-16 08:07 UTC, m1raynee commented on dislash/slash_commands/slash_client.py
> +                    return True
```suggestion
check = lambda ctx: True
```
Simmilar to [this](https://github.com/EQUENOS/dislash.py/pull/35/files#r671050405)

2021-07-16 08:10 UTC, m1raynee requested changes
In general, I noted all the wrong things that I found

2021-07-16 13:41 UTC, MisileLab commented
@m1raynee Can you pull request to my fork repository?

2021-07-24 04:48 UTC, MisileLab commented on dislash/slash_commands/slash_client.py
> +                    return True
but pep-8 say do not assign a lambda expression, use a def

2021-07-24 04:48 UTC, MisileLab commented on dislash/slash_commands/slash_client.py
> +                    return True
but pep-8 say do not assign a lambda expression, use a def

2021-07-24 04:56 UTC, m1raynee commented on dislash/slash_commands/slash_client.py
> +                    return True
when ```suggestion
            def check(inter):
                return True
```

2021-07-25 16:20 UTC, m1raynee reviewed
Something strange starts happening here

2021-07-25 16:20 UTC, m1raynee commented on dislash/slash_commands/slash_client.py
> +                    return True
I'm tired of explaining to you for the third time what is wrong here. I ask you to carefully reread my comments on GitHub and messages in Discord.

2021-07-25 16:20 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +               items):
You don't pushed it

2021-07-25 16:20 UTC, m1raynee commented on dislash/interactions/message_components.py
> +MenuOption = SelectOption
What the heck is going on here?

2021-07-26 08:45 UTC, MisileLab commented on dislash/interactions/message_components.py
> +MenuOption = SelectOption
hmm ide broken lol

2021-07-26 09:08 UTC, MisileLab commented
I pushed.

2021-07-26 09:20 UTC, m1raynee commented on dislash/interactions/message_components.py
> +    link = 5
Why did you pass it by? You can do this, here is an example from [discord.py].(https://github.com/Rapptz/discord.py/blob/7d9074db8a434995d9e0ae27adb2432b51219c99/discord/enums.py#L310-L349)

2021-07-26 09:24 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +
```suggestion
```
Extra line

2021-07-26 09:24 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +
```suggestion
```
Extra line

2021-07-26 09:28 UTC, m1raynee commented on dislash/slash_commands/slash_core.py
> +    return decorator
```suggestion
    return decorator
```
Extra line

2021-07-27 14:57 UTC, MisileLab commented
pushed

2021-08-04 22:54 UTC, closed without merging